{% set version = "4.59" %}

package:
  name: glpk
  version: {{ version }}

source:
  fn: glpk-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/glpk/glpk-{{ version }}.tar.gz
  md5: c84ce7b8286ab91f2e871cd82050e2fe

build:
   number: 0

   {% set VC_VERSION = os.environ.get('VC_VERSION', '15.0') %}
   msvc_compiler: {{ VC_VERSION }}
   features:
     - vc{{ VC_VERSION.split('.')[0] }}  # [win]

requirements:
  build:
    - vc  # [win]
    - gmp  #[not win]

  run:
    - vc {{ VC_VERSION }}  # [win]
    - gmp  # [not win]

test:
  requires:
    - python
  files:
    - test.c
    - setup.py
    - spam.c
    - plan.mps

  commands:
    - glpsol --mps plan.mps
    - python setup.py test

about:
  home: https://www.gnu.org/software/glpk/
  license: GNU General Public License v3
  summary: GNU Linear Programming Kit

extra:
  recipe-maintainers:
    - jjhelmus
    - aebrahim
    - jakirkham
