appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: jaXEsj9pu5Af2Nol8WoFO2KxsV71k2CmGDShy4bF9jbS72WyQSO2+0Ho5e0YabkgUwwZ0tPXumAB7sQf3J1wXP8WptxTRr08zs5ncYOFMHcWDVR8tPcSbiN3iqWvUPEQV8O1zbPwkGgAIWRauevTWfIYlRaQWVW4KYdNS3vOAhzc35wiNSOK+oECvZ7qyW/fIlwudmRTfAG8yl4w1JPz3zKhoVar5qke8UzgLRjWkJYVSEmR5OKqy0gObiJpmr7mIsgPfaujUvaE9iBdpmb+SqRBJIJ9g46mCoosQtcQuTb0Ae3tZHV9MOl7lxdCxw41loOSfXUnji/c+yGL6lo0bsCkLqClX4ADJzIuw4IGRd7ENXhdO92JeQkHmret46cdiQKAJB8mWQEEw+rzSuFzyiAdtxo0plbwd4vonm9j8LLBejfucSwAoSA338RRyHEiv2NqnSG2PIG1DukYLLhQUxHtsgmFIwdKPqIA14xFkmRuamv4dBCbOahc6PqUif+T6WXDp/+O5aKi0JS6VqsllJbQTTyVeqT+zANs/QKRyxhehlDtqle0FFAEDWOyGrt1ymf+x2FxV97y+45sPcCbgx7GHERlTfz2ysGHfOfpAoNlk1FLGdJ92o1CykLYK9xxZtr4SPv7tlXyvUtic/jmvYGSQgIcSB+9n9Ch7o+J8Ds=}
conda_forge_output_validation: true
